# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f07a517f0d846e62374afd43306b2ca0c82eb304a37a27ce4465302dbf5154a4e7cde37b282b7f784cbee42e2c123ce29a9c64155f23c9f99d32271268949dd1

test:
  secret_key_base: ed2457860b5dce93ecdc289447d2126bfe77df713921073fea97b33d578812f39a8a0d8ed8adab06e0534acfe191e383dfcb9c3e8d13c501582266b9ef31d883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
